import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Not Found",
  description: "Generated by create next app",
};

export default function NotFound() {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>Not Found Page</h1>
        <p>We cannot find page</p>
      </body>
    </html>
  );
}
